config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"
  resources :cocktails, only: [:index, :new, :show, :create, :edit, :destroy] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id,  uniqueness: { scope: [:ingredient_id] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktails_path
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :photo, :photo_cache)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
     before_action :set_cocktail, only: [:create, :new, :show, :edit, :update]

 def index
   @doses = Dose.all
 end

 def show
 end

 def new
   @dose = Dose.new
   @ingredient = Ingredient.all
 end

 def create
   @dose = @cocktail.doses.build(dose_params)
   if @dose.save
     redirect_to cocktail_path(@cocktail)
   else
     render :new
   end
 end

 def edit
 end

 def update
 end

 def destroy
   @dose = Dose.find(params[:id])
   @dose.destroy
   redirect_to cocktail_path(@dose.cocktail)
 end

  private
   # Use callbacks to share common setup or constraints between actions.
   def set_cocktail
     @cocktail = Cocktail.find(params[:cocktail_id])
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def dose_params
     params.require(:dose).permit(:description, :ingredient_id)
   end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:create, :new, :show, :edit, :update, :destroy]
  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @Ingredient = Ingredient.new
  end

  def edit
  end

  def create
    @Ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_path
    else
      render :new
    end
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      render :edit
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:Ingredient).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
  url('<%= cocktail.photo.present? ? cl_image_path(cocktail.photo, height: 300, width: 400, crop: :fill) : cl_image_path('https://unsplash.it/500/400') %>')">
  <div class="card-description">
    <h2><%= cocktail.name %></h2>
  </div>
  <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
</div>

app/views/cocktails/_form.html.erb
<div class="container">
 <div class="row">
   <div class="col-xs-12 col-sm-6 col-sm-offset-3">
   <%= simple_form_for @cocktail do |f| %>
     <%= f.error_notification %>
       <%= f.input :name, placeholder: "Name of the cocktail"%>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
       <%= f.submit "Submit", class: "btn btn-primary" %>
   <% end %>
   </div>
 </div>
</div>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>
<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<h1 class="text-center">Cocktails</h1>
<div class="container">
 <div class="row">
   <% @cocktails.each do |cocktail| %>
   <div class="col-xs-12 col-sm-6 col-md-3">
     <%= render "card", cocktail: cocktail %>
     <%= link_to "Edit", edit_cocktail_path(cocktail), class: "btn btn-primary" %>
     <%= link_to "Delete", cocktail_path(cocktail), method: :delete, class: "btn btn-primary"%>
   </div>
   <% end %>
 </div>
 <%= link_to 'New cocktail', new_cocktail_path, class: "btn btn-danger" %>
</div>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>

app/views/cocktails/show.html.erb
<% content_for(:name) do %>
  <%= @cocktail.name %>
<% end %>

<p>
  <strong>Cocktail:</strong>
  <%= @cocktail.name %>
</p>

<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

<ul>
  <% @cocktail.doses.each do |dose| %>
    <li><%= dose.ingredient.name %> - <%= dose.description %>
    <%= link_to "Delete", dose_path(dose), method: :delete, class: "btn btn-danger"%>
    </li>
  <% end %>
</ul>

<%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>
<%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>

<% content_for(:after_js) do %>
<script>
  $(document).ready(function(){
    alert("<%= @cocktail.name %>");
  })
</script>
<% end %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/_form.html.erb
<h1 class="text-center">Create a dose</h1>
<div class="container">
 <div class="row">
   <div class="col-xs-12 col-sm-6 col-sm-offset-3">
   <%= simple_form_for [@cocktail, @dose] do |f| %>
     <%= f.error_notification %>
     <div class="form-inputs">
        <%= f.association :ingredient %>
        <%= f.input :description, placeholder: "Quantity"%>
     </div>
     <div class="form-actions">
       <%= f.button :submit %>
     </div>
   <% end %>
   </div>
 </div>
</div>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

<%= render 'form', dose: @dose %>

<%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>